_schema: _schema
source: /docs/
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs:
    path: _docs
    name: Docs
    icon: dock
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_drafts:
    path: docs/_drafts
    name: Docs Drafts
    icon: drafts
    disable_url: false
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.docs_posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.docs_posts[*].tags
        cascade: true
    create:
      path: ''
      publish_to: docs_posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_posts:
    path: docs/_posts
    name: Docs Posts
    icon: compost
    disable_url: false
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.docs_posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.docs_posts[*].tags
        cascade: true
    add_options:
      - name: Add Post
      - name: Add Draft
        collection: docs_drafts
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pets:
    path: docs/_pets
    name: Pets
    icon: pets
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  portfolio:
    path: _portfolio
    name: Portfolio
    icon: portrait
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  recipes:
    path: _recipes
    name: Recipes
    icon: local_dining
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  test_drafts:
    path: test/_drafts
    name: Test Drafts
    icon: drafts
    disable_url: false
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.test_posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.test_posts[*].tags
        cascade: true
    create:
      path: ''
      publish_to: test_posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  test_posts:
    path: test/_posts
    name: Test Posts
    icon: sports
    disable_url: false
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.test_posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.test_posts[*].tags
        cascade: true
    add_options:
      - name: Add Post
      - name: Add Draft
        collection: test_drafts
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
_snippets_imports:
  jekyll: true
timezone: Pacific/Auckland
markdown:
  engine: kramdown
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: true
    quotes: ‘’“”
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: true
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
